/*
 * SPDX-License-Identifier: LGPL-2.1-or-later
 *
 * Copyright (C) 2026 deviationist
 *
 * Cockpit-bound helpers for the guided control-user wizard: create a
 * least-privilege NUT control user in upsd.users and reload upsd. Pure block
 * building lives in control-user-parse.ts.
 *
 * SECURITY: upsd.users holds plaintext NUT passwords and must stay 0640
 * root:nut (world-unreadable, group-readable by the nut service). This is the
 * ONE place UPSide writes that file — and only on an explicit wizard action via
 * superuser "require" (admin prompt). The original owner is preserved, the file
 * is re-chmodded 0640 after writing, and the .bak (which also contains other
 * users' passwords) is locked down the same way. The password is generated with
 * the browser CSPRNG and never logged.
 */

import cockpit from 'cockpit';

import { appendStanza, parseConfSections, removeStanza } from './setup-parse';
import { UserGrants, addSetAction, addUpsmonRole, buildMonitorBlock, buildUserBlock, ensureInstcmds, parseUserBlock, setUpsmonRole } from './control-user-parse';
import type { UpsmonType } from './upsmon-parse';

export * from './control-user-parse';

const _ = cockpit.gettext;

const USERS_PATHS = ["/etc/nut/upsd.users", "/etc/ups/upsd.users"];
const SERVER_UNIT = "nut-server.service";

/** A cryptographically-strong hex password (24 bytes → 48 hex chars). */
export function generatePassword(): string {
    const bytes = new Uint8Array(24);
    crypto.getRandomValues(bytes);
    return Array.from(bytes, b => b.toString(16).padStart(2, "0")).join("");
}

async function read(path: string, superuser: "try" | "require"): Promise<string | null> {
    const file = cockpit.file(path, { superuser });
    try {
        return await file.read();
    } catch {
        return null;
    } finally {
        file.close();
    }
}

/** Locate upsd.users (defaults to the /etc/nut path if none exists yet). */
export async function findUsersFile(): Promise<string> {
    for (const p of USERS_PATHS) {
        if (await read(p, "try") !== null)
            return p;
    }
    return USERS_PATHS[0];
}

/** Existing user/section names in upsd.users (best-effort; empty for non-admins). */
export async function listControlUsers(): Promise<string[]> {
    const path = await findUsersFile();
    return parseConfSections(await read(path, "try"));
}

/**
 * Replace upsd.users with `next` (given the `current` text for backup), keeping
 * the file's owner and 0640 perms, then reload upsd. The lone privileged-write
 * path, shared by create + reuse. The .bak also holds plaintext passwords, so
 * it's locked down identically.
 */
async function writeUsersFile(path: string, next: string, current: string | null): Promise<void> {
    // Preserve the existing owner (typically root:nut); default to that for a new file.
    let owner = "root:nut";
    if (current !== null) {
        try {
            const o: string = await cockpit.spawn(["stat", "-c", "%U:%G", path], { superuser: "require", err: "message" });
            if (/^\S+:\S+$/.test(o.trim()))
                owner = o.trim();
        } catch { /* keep the default */ }

        const bak = cockpit.file(`${path}.bak`, { superuser: "require" });
        try {
            await bak.replace(current);
        } finally {
            bak.close();
        }
        await cockpit.spawn(["chmod", "640", `${path}.bak`], { superuser: "require", err: "message" }).catch(() => { /* best effort */ });
        await cockpit.spawn(["chown", owner, `${path}.bak`], { superuser: "require", err: "message" }).catch(() => { /* best effort */ });
    }

    const file = cockpit.file(path, { superuser: "require" });
    try {
        await file.replace(next);
    } finally {
        file.close();
    }

    // Lock the file back down — replace() can land it world-readable otherwise.
    await cockpit.spawn(["chmod", "640", path], { superuser: "require", err: "message" });
    await cockpit.spawn(["chown", owner, path], { superuser: "require", err: "message" });

    // SIGHUP upsd so it re-reads upsd.users without dropping the driver/connections.
    await cockpit.spawn(["systemctl", "reload", SERVER_UNIT], { superuser: "require", err: "message" });
}

/**
 * Create a control user: append its block to upsd.users, lock down permissions,
 * and reload upsd. The password must already be generated by the caller (so it
 * can be shown once / stored). Throws if the name already exists.
 */
export async function createControlUser(name: string, password: string, instcmds: string[]): Promise<{ path: string }> {
    const path = await findUsersFile();
    const current = await read(path, "require");
    if (current && parseConfSections(current).includes(name))
        throw new Error(cockpit.format(_("A NUT user named \"$0\" already exists in upsd.users."), name));
    await writeUsersFile(path, appendStanza(current, buildUserBlock(name, password, instcmds)), current);
    return { path };
}

/**
 * Create a secondary-login user: the upsd.users entry a remote upsmon logs in
 * as on a netserver primary — a password + `upsmon secondary`, no command
 * grants. Same privileged write path as a control user, just no instcmds.
 */
export async function createSecondaryUser(name: string, password: string): Promise<{ path: string }> {
    return createControlUser(name, password, []);
}

/**
 * Set the monitor (upsmon) user to a password + `upsmon <role>`, nothing else —
 * the least-privilege identity upsmon's MONITOR line logs in as on a UPS-owning
 * host (role `primary`), separate from any control user. Upsert semantics:
 * replaces an existing same-named block (so re-running the Shutdown step rotates
 * the password rather than dead-ending on "already exists"), else appends. Its
 * password is purely internal — UPSide writes it to both upsd.users and
 * upsmon.conf and the operator never needs to see it.
 */
export async function setMonitorUser(name: string, password: string, role: UpsmonType): Promise<{ path: string }> {
    const path = await findUsersFile();
    const current = await read(path, "require");
    const without = current ? removeStanza(current, name) : "";
    await writeUsersFile(path, appendStanza(without, buildMonitorBlock(name, password, role)), current);
    return { path };
}

/**
 * Force an existing user's upsmon role to `role` (e.g. upgrade a reused user to
 * `primary` so a primary MONITOR line authenticates). Never touches the
 * password. Returns whether the file changed.
 */
export async function ensureUpsmonRole(name: string, role: UpsmonType): Promise<{ changed: boolean }> {
    const path = await findUsersFile();
    const current = await read(path, "try");
    if (current === null)
        throw new Error(_("Administrator access is needed to read upsd.users."));
    if (!parseUserBlock(current, name))
        throw new Error(cockpit.format(_("\"$0\" isn't in upsd.users."), name));
    const next = setUpsmonRole(current, name, role);
    if (next === current)
        return { changed: false };
    await writeUsersFile(path, next, current);
    return { changed: true };
}

/** Read an existing user's grants (password + instcmds + upsmon role). Needs
 *  admin to see the password; returns null for a missing user or non-admin.
 *  Uses "try" so it doesn't pop an admin prompt just from inspecting a name. */
export async function readControlUser(name: string): Promise<UserGrants | null> {
    return parseUserBlock(await read(await findUsersFile(), "try"), name);
}

/**
 * Make an existing control user fully capable for UPSide, adding only what's
 * missing and never touching its password:
 *   - an `upsmon` role, so a no-op LOGIN can verify the credentials;
 *   - `actions = SET`, so it can change read-write variables (upsrw).
 * We don't read or return the password — when reusing a user the operator types
 * it, so UPSide validates and stores what they entered, never a credential
 * lifted out of upsd.users. Optionally also grant `instcmds` (the commands the
 * GUI displays) so no control button dead-ends on ACCESS-DENIED. Returns which
 * grants were added.
 */
export async function ensureControlGrants(name: string, instcmds: string[] = []): Promise<{ grantedUpsmon: boolean, grantedSet: boolean, grantedCmds: string[] }> {
    const path = await findUsersFile();
    const current = await read(path, "try");
    if (current === null)
        throw new Error(_("Administrator access is needed to read upsd.users."));
    const g = parseUserBlock(current, name);
    if (!g)
        throw new Error(cockpit.format(_("\"$0\" isn't in upsd.users."), name));
    let next = current;
    if (!g.hasUpsmon)
        next = addUpsmonRole(next, name);
    if (!g.hasSet)
        next = addSetAction(next, name);
    // The displayed instant commands the user doesn't already hold (skipped
    // entirely if it's `instcmds = ALL`).
    const grantedCmds = g.allCmds ? [] : instcmds.filter(c => !g.instcmds.includes(c));
    if (instcmds.length)
        next = ensureInstcmds(next, name, instcmds);
    if (next === current)
        return { grantedUpsmon: false, grantedSet: false, grantedCmds: [] };
    await writeUsersFile(path, next, current);
    return { grantedUpsmon: !g.hasUpsmon, grantedSet: !g.hasSet, grantedCmds };
}
