/*
 * SPDX-License-Identifier: LGPL-2.1-or-later
 *
 * Copyright (C) 2026 deviationist
 *
 * Cockpit-bound helpers for the guided control-user wizard: create a
 * least-privilege NUT control user in upsd.users and reload upsd. Pure block
 * building lives in control-user-parse.ts.
 *
 * SECURITY: upsd.users holds plaintext NUT passwords and must stay 0640
 * root:nut (world-unreadable, group-readable by the nut service). This is the
 * ONE place UPSide writes that file — and only on an explicit wizard action via
 * superuser "require" (admin prompt). The original owner is preserved, the file
 * is re-chmodded 0640 after writing, and the .bak (which also contains other
 * users' passwords) is locked down the same way. The password is generated with
 * the browser CSPRNG and never logged.
 */

import cockpit from 'cockpit';

import { appendStanza, parseConfSections } from './setup-parse';
import { buildUserBlock } from './control-user-parse';

export * from './control-user-parse';

const _ = cockpit.gettext;

const USERS_PATHS = ["/etc/nut/upsd.users", "/etc/ups/upsd.users"];
const SERVER_UNIT = "nut-server.service";

/** A cryptographically-strong hex password (24 bytes → 48 hex chars). */
export function generatePassword(): string {
    const bytes = new Uint8Array(24);
    crypto.getRandomValues(bytes);
    return Array.from(bytes, b => b.toString(16).padStart(2, "0")).join("");
}

async function read(path: string, superuser: "try" | "require"): Promise<string | null> {
    const file = cockpit.file(path, { superuser });
    try {
        return await file.read();
    } catch {
        return null;
    } finally {
        file.close();
    }
}

/** Locate upsd.users (defaults to the /etc/nut path if none exists yet). */
export async function findUsersFile(): Promise<string> {
    for (const p of USERS_PATHS) {
        if (await read(p, "try") !== null)
            return p;
    }
    return USERS_PATHS[0];
}

/** Existing user/section names in upsd.users (best-effort; empty for non-admins). */
export async function listControlUsers(): Promise<string[]> {
    const path = await findUsersFile();
    return parseConfSections(await read(path, "try"));
}

/**
 * Create a control user: append its block to upsd.users (backing the file up
 * first), lock down permissions, and reload upsd so the user takes effect. The
 * password must already be generated by the caller (so it can be shown once /
 * stored). Throws if the name already exists or any privileged step fails.
 */
export async function createControlUser(name: string, password: string, instcmds: string[]): Promise<{ path: string }> {
    const path = await findUsersFile();
    const current = await read(path, "require");

    if (current && parseConfSections(current).includes(name))
        throw new Error(cockpit.format(_("A NUT user named \"$0\" already exists in upsd.users."), name));

    // Preserve the existing owner (typically root:nut); default to that for a new file.
    let owner = "root:nut";
    if (current !== null) {
        try {
            const o: string = await cockpit.spawn(["stat", "-c", "%U:%G", path], { superuser: "require", err: "message" });
            if (/^\S+:\S+$/.test(o.trim()))
                owner = o.trim();
        } catch { /* keep the default */ }
    }

    const next = appendStanza(current, buildUserBlock(name, password, instcmds));

    // Back up first (the backup also holds plaintext passwords).
    if (current !== null) {
        const bak = cockpit.file(`${path}.bak`, { superuser: "require" });
        try {
            await bak.replace(current);
        } finally {
            bak.close();
        }
        await cockpit.spawn(["chmod", "640", `${path}.bak`], { superuser: "require", err: "message" }).catch(() => { /* best effort */ });
        await cockpit.spawn(["chown", owner, `${path}.bak`], { superuser: "require", err: "message" }).catch(() => { /* best effort */ });
    }

    const file = cockpit.file(path, { superuser: "require" });
    try {
        await file.replace(next);
    } finally {
        file.close();
    }

    // Lock the file back down — replace() can land it world-readable otherwise.
    await cockpit.spawn(["chmod", "640", path], { superuser: "require", err: "message" });
    await cockpit.spawn(["chown", owner, path], { superuser: "require", err: "message" });

    // SIGHUP upsd so it re-reads upsd.users without dropping the driver/connections.
    await cockpit.spawn(["systemctl", "reload", SERVER_UNIT], { superuser: "require", err: "message" });

    return { path };
}
